# Dockerfile.ui
FROM python:3.10-slim

WORKDIR /app

# Install deps
COPY ui/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy app code
COPY ui ./ui

EXPOSE 8000

CMD ["streamlit", "run", "ui/app.py", "--server.port", "8000", "--server.address", "0.0.0.0"]
