FROM python:3.10-slim

WORKDIR /app

# Install OS deps
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

COPY actions/ /app/actions/
COPY actions/requirements.txt /app/actions/requirements.txt


# Install ONLY the custom deps
RUN pip install --no-cache-dir -r actions/requirements.txt

COPY actions /app/actions

ENV PYTHONPATH=/app

EXPOSE 5055

CMD ["rasa", "run", "actions", "--port", "5055"]
