FROM rasa/rasa:3.6.21-full

WORKDIR /app

COPY config.yml domain.yml credentials.yml endpoints.yml ./
COPY data ./data
COPY models ./models
# If adding extra dependencies:
# RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 5005

CMD ["run", "--enable-api", "--cors", "*"]
